### ISSUE TITLE
third covid cohort missing info

### ISSUE THREAD

**Issue by tinarwhite** [nqureshi/ev-winners#1]
Issue with some missing info from this Covid-19 cohort. Tina White and the Covid Watch project sometimes gets left out of these lists, perhaps because the MR post was made later as an addition in May 2020 with only two projects.

"This is an Early Response prize, for their critical and timely work to boost the quality of these apps and to make them more privacy-friendly"

Link:
https://marginalrevolution.com/marginalrevolution/2020/05/emergent-ventures-prize-winners-third-cohort.html

**Comment by nqureshi** [comment]
Updated!
